export const Cities = [
  "Karachi",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Multan",
  "Hyderabad",
  "Gujranwala",
  "Peshawar",
  "Quetta",
  "Islamabad",
  "Sargodha",
  "Sialkot",
  "Bahawalpur",
  "Sukkur",
  "Jhang",
  "Sheikhupura",
  "Larkana",
  "Gujrat",
  "Mardan",
  "Kasur",
  "Rahim Yar Khan",
  "Sahiwal",
  "Okara",
  "Wah Cantonment",
  "Dera Ghazi Khan",
  "Mingora",
  "Mirpur Khas",
  "Chiniot",
  "Kamoke",
  "Mandi Bahauddin",
  "Jhelum",
  "Sadiqabad",
  "Khanewal",
  "Jacobabad",
  "Muzaffargarh",
  "Khanpur",
  "Gojra",
  "Bahawalnagar",
  "Abbottabad",
  "Muridke",
  "Pakpattan",
  "Khuzdar",
  "Jaranwala",
  "Chishtian",
  "Daska",
  "Mandi Yazman",
  "Chakwal",
  "Kamalia",
  "Tando Adam",
  "Khairpur",
  "Dera Ismail Khan",
  "Vehari",
  "Nowshera",
  "Dadu",
  "Wazirabad",
  "Khushab",
  "Charsadda",
  "Swabi",
  "Qila Sheikhupura",
  "Panama",
  "Havelian",
  "Lodhran",
  "Mianwali",
  "Muzaffarabad",
  "Jamshoro",
  "Chunian",
  "Tando Allahyar",
  "Kot Adu",
  "Nawabshah",
  "Bagh",
  "Kharian",
  "Liaquatpur",
  "Kambar",
  "Moro",
  "Abbottabad",
  "Aliabad",
  "Amir Chah",
  "Arifwala",
  "Awaran",
  "Badah",
  "Barkhan",
  "Basirpur",
  "Belah",
  "Bhag",
  "Bhakkar",
  "Bhalwal",
  "Bhan",
  "Bhopalwala",
  "Bhit Shah",
  "Bozdar Wada",
  "Bunner",
  "Chak Two Hundred Forty-Nine Thal Development Authority",
  "Chaman",
  "Chenki",
  "Chhor",
  "Chitral",
  "Daggar",
  "Dalbandin",
  "Daraban",
  "Darya Khan",
  "Dera Bugti",
  "Dhudial Chakwal",
  "Digri",
  "Duki",
  "Dullewala",
  "Dunyapur",
  "Eminabad",
  "Eri",
  "Faqirwali",
  "Fazalpur",
  "Fort Abbas",
  "Gaddani",
  "Gambat",
  "Garh Maharaja",
  "Garhi Khairo",
  "Garhi Yasin",
  "Ghauspur",
  "Ghotki",
  "Gilgit",
  "Girdan",
  "Gujar Khan",
  "Gujarati",
  "Gujjar Khan",
  "Hala",
  "Haripur",
  "Hasilpur",
  "Haveli",
  "Hayatabad",
  "Hazro",
  "Head Marala",
  "Hub",
  "Hujra Shah Muqim",
  "Hunza",
  "Hussainabad",
  "Ishqal Bindhi",
  "Jacobabad",
  "Jampur",
  "Jatoi Shimali",
  "Jauharabad",
  "Jhang Sadr",
  "Jiwani",
  "Johi",
  "Kadhan",
  "Kahna",
  "Kahror Pakka",
  "Kahuta",
  "Kakul",
  "Kala Shah Kaku",
  "Kalat",
  "Kalur Kot",
  "Kamra",
  "Kandiaro",
  "Kandhkot",
  "Kanpur",
  "Karampur",
  "Karak",
  "Kashmor",
  "Kathor",
  "Kazi Ahmad",
  "Khairpur Nathan Shah",
  "Khairpur Mirs",
  "Khairpur Tamewali",
  "Khambi",
  "Khanaspur",
  "Khanga Dogran",
  "Kharan",
  "Kharian Cantonment",
  "Khanpur Mahar",
  "Khanspur",
  "Khanwal",
  "Khawaja Gung",
  "Khidrābād",
  "Khushāb",
  "Khuzdār",
  "Kot Addu",
  "Kot Diji",
  "Kot Ghulām Muhammad",
  "Kot Malik Barkhurdar",
  "Kot Mūmin",
  "Kot Rādha Kishan",
  "Kot Samāba",
  "Kotli Lohārān",
  "Kotli",
  "Kotri",
  "Kundian",
  "Kunjah",
  "Kurram Agency",
  "Lahār",
  "Lakki Marwat",
  "Lārkāna",
  "Leiah",
  "Liliani",
  "Loralai",
  "Lortu",
  "Māmu Kānjan",
  "Malakand",
  "Malakwal",
  "Mamū Kanjan",
  "Manānwāla",
  "Mānānwāla",
  "Mandi Zāhīd Khān",
  "Manglaur",
  "Mangla",
  "Mangowāl",
  "Mānsa",
  "Mānsehra",
  "Mardān",
  "Mari",
  "Mastung",
  "Matli",
  "Mātli",
  "Mehar",
  "Mehmūd Khān Khoso",
  "Mehrabpur",
  "Mian Channūn",
  "Mianwāli",
  "Mināwarā",
  "Mitha Tiwāna",
  "Mithi",
  "Modle Town",
  "Moro",
  "Multān",
  "Mūsa Khel Bāzār",
  "Muzaffar Garh",
  "Nārowāl",
  "Naushahra",
  "Naukot",
  "Nāushahro Fīroz",
  "Nawābshāh",
  "Nawābshāh Cantonment",
  "Noon Bagla",
  "Nowshera Cantonment",
  "Okāra Cantonment",
  "Padīdan",
  "Pahārpur",
  "Pākpattan",
  "Pālāmpur",
  "Pālang",
  "Pattoki",
  "Peshāwar",
  "Phalia",
  "Phulji",
  "Pind Dādan Khān",
  "Pindi Bhattiān",
  "Pindi Gheb",
  "Piplān",
  "Pishin",
  "Punāsa",
  "Quaidabad",
  "Rabwāh",
  "Rāiwind",
  "Rājanpur",
  "Rāwalpindi",
  "Risālpur",
  "Rohri",
  "Rustam Jān Khān",
  "Rustam",
  "Sādiqābād",
  "Sakrand",
  "Sambriāl",
  "Sānghar",
  "Sangla Hill",
  "Sanjwāl",
  "Sara-e-Naurang",
  "Sargodha",
  "Sehwān Sharīf",
  "Serai",
  "Sethārja Old",
  "Shabqadar",
  "Shahr Sultan",
  "Shahrīārī",
  "Shāhdādpur",
  "Shahdādpur",
  "Shāhdādkot",
  "Shāhdādpur",
  "Shahrīārī",
  "Shāhjānwāla",
  "Shahpur Chakar",
  "Shahpur",
  "Shakargarr",
  "Shāmli",
  "Shekhūpura",
  "Shikārpur",
  "Shingli Bāla",
  "Shorkot",
  "Shorko",
  "Shujāābād",
  "Sibi",
  "Sialkot",
  "Sibi",
  "Sillānwāli",
  "Sinjhoro",
  "Soianwāla",
  "Sukkur",
  "Swābi",
  "Tāngi",
  "Tāndo Ādam",
  "Tāndliānwāla",
  "Tando Muhammad Khan",
  "Tando Muhammad Khān",
  "Tāndo Allāhyār",
  "Tank",
  "Tarakeswar",
  "Taunsa",
  "Taxila",
  "Toba Tek Singh",
  "Toba Tek Singh",
  "Tulamba",
  "Ubauro",
  "Uthal",
  "Vihāri",
  "Wāh Cantonment",
  "Wāris Khān",
  "Wārāh",
  "Wāris Khān",
  "Wāh Cantonment",
  "Wārāh",
  "Zafarwāl",
  "Zahir Pir",
  "Zāhir Pīr",
  "Zaība Bākewāla",
  "Ziarat",
  "Ziarat",
  "Ziārat",
  "Ziārat Colony",
];
